PATHS:
 LEVELS_DIRECTORY: public/game/assets/levels

DEFAULTS:
 MASTER_USER_NAME: "1dayitwillmake"
 TITLE_SCREEN_LEVEL: TitleScreen

SECRET:
 TOKEN: 1C6D7667A63BD6C92837C98B3229F
 SALT: 4418jd3

SPECIAL_STRINGS:
 LEVEL_JSON:
  USER_NAME_MASK: "#{user_name}"