PATHS:
 LEVELS_DIRECTORY: public/game/assets/levels

DEFAULTS:
 MASTER_USER_NAME: "1dayitwillmake"
 MASTER_USER_ID: "1"
 TITLE_SCREEN_LEVEL: TitleScreen
 MINIMUM_SCORES_FOR_BETA_LEVELS: 10

SECRET:
 TOKEN: 1C6D7667A63BD6C92837C98B3229F
 SALT: 4418jd3

SPECIAL_STRINGS:
 LEVEL_JSON:
  USER_NAME_MASK: "#{user_name}"